name: fasal_doctor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Image handling
  image_picker: ^1.0.7
  image: ^4.1.7
  
  # Permissions
  permission_handler: ^11.3.0
  
  # UI enhancements
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  
  # File handling
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.14.4
  
  # API handling
  dio: ^5.4.1
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  pytorch_lite: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/model.pt
    - assets/labels.txt
    - .env

